# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Evan Moss
tagline:          'Blog'
description:      'A third year computer science student at the University of Edinburgh. Follow me on twitter <a href="https://twitter.com/ev_jo_mo" target="_blank">@ev_jo_mo</a>.'
url:              www.evanmoss.co.uk
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

plugins: [jekyll-paginate]

paginate: 5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/hyde
